apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: hasura-hpa-memory
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hasura
  minReplicas: 1
  maxReplicas: 2
  metrics: 
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85