apiVersion: v1
kind: Secret
metadata:
  name: hasura-secret
type: Opaque
stringData:
   HASURA_GRAPHQL_ADMIN_SECRET: mysecret
   HASURA_GRAPHQL_DATABASE_URL: postgres://postgresadmin:admin124@postgres:5432/postgresdb