apiVersion: v1
kind: Pod 
metadata:
  name: portal-de-noticias
  labels: 
    app: portal-de-noticias
spec:
  containers: 
    - name: portal-de-noticias
      image: aluracursos/portal-noticias:1
      ports:
       - containerPort: 80
      envFrom:
        - configMapRef:
            name: portal-config