apiVersion: v1
kind: Pod
metadata: 
    name: db-mysql
    labels:
        app: db-mysql
spec:
      containers:
        - name: db-mysql
          image: mysql:latest
          ports: 
            - containerPort: 3306
          env: 
            - name: 'MYSQL_ROOT_PASSWORD'
              value: '123554849'
            - name: 'MYSQL_DATABASE'
              value: 'teste'
            - name: 'MYSQL_USER'
              value: 'bob'
            - name: 'MYSQL_PASSWORD'
              value: '123554849'