apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
spec:
    replicas: 3
    template:
        metadata:
            name: ngix-pod
            labels:
              app: ngix-pod
        spec:
            containers:
                - name: ngix-container   
                  image: nginx:1
                  ports:
                    - containerPort: 80
    selector:
        matchLabels:
            app: ngix-pod