apiVersion: apps/v1
kind: ReplicaSet
metadata: 
    name: pod-1-replicaset
spec: 
    template:
        metadata: 
            name: pod-1
            labels:
                app: first-pod
        spec:
            containers:
                - name: container-pod-1
                  image: nginx:latest
                  ports:
                   - containerPort: 80  
    replicas: 3
    selector:
        matchLabels:
            app: first-pod